# Generated by Django 4.2.18 on 2025-01-28 23:29

from django.db import migrations

def import_groups(apps, schema_editor):
    DbGroup = apps.get_model("slims", "DbGroup")
    Group = apps.get_model("auth", "Group")
    groups = []
    for group in DbGroup.objects.all():
        groups.append(Group(pk=group.pk, name=group.db_group))
    Group.objects.bulk_create(groups, 100)

class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0001_charset')
    ]

    operations = [
        migrations.RunPython(import_groups),
    ]
