# Generated by Django 4.2.18 on 2025-01-29 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('slims', '0002_migration_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlane',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
    ]
