# Generated by Django 4.2.18 on 2025-02-13 23:29

from django.db import migrations, models
import slims.models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0006_add_group_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='runlane',
            name='concentration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='runlane',
            name='random_dir',
            field=models.CharField(blank=True, default=slims.models.generate_random_string, max_length=15, null=True, unique=True),
        ),
    ]
