# Generated by Django 4.2.18 on 2025-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0007_alter_run_submitted_alter_runlane_concentration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlane',
            name='concentration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
