# Generated by Django 4.2.18 on 2025-02-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreomics', '0003_submission_submission_type'),
        ('slims', '0008_alter_runlane_concentration'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlane',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='coreomics.submission'),
        ),
    ]
