# Generated by Django 4.2.18 on 2025-02-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0010_alter_runlane_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=100)),
                ('repository_subpath', models.CharField(max_length=100)),
                ('transfer_type', models.CharField(choices=[('COPY', 'COPY'), ('LINK', 'LINK')], default='LINK', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'Transfer In Progress'), ('ERROR', 'Error'), ('COMPLETE', 'Complete')], default='NEW', max_length=15)),
                ('lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='slims.runlane')),
            ],
        ),
    ]
