# Generated by Django 5.1.6 on 2025-03-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0011_lanedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanedata',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
