# Generated by Django 5.1.6 on 2025-03-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('slims', '0012_lanedata_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlane',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='runlane',
            name='random_dir',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
