# Generated by Django 5.1.6 on 2025-03-06 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0013_alter_runlane_group_alter_runlane_random_dir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='machine',
            new_name='machine_name',
        ),
    ]
