# Generated by Django 5.1.6 on 2025-03-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0014_rename_machine_run_machine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunType',
            fields=[
                ('id', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.SlugField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('base_directory', models.CharField(blank=True, max_length=75, null=True)),
                ('run_types', models.ManyToManyField(to='slims.runtype')),
            ],
        ),
    ]
