# Generated by Django 5.1.6 on 2025-03-07 00:02

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0015_runtype_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='slims.machine'),
        ),
        migrations.AddField(
            model_name='run',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='slims.runtype'),
        ),
    ]
