# Generated by Django 5.1.6 on 2025-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0016_run_machine_run_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanedata',
            name='data_path',
            field=models.CharField(max_length=200),
        ),
    ]
