# Generated by Django 5.1.6 on 2025-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0020_runtype_enabled_alter_machine_run_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='unique_id',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
