# Generated by Django 5.1.6 on 2025-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0022_run_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
