# Generated by Django 5.1.6 on 2025-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slims', '0023_alter_run_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
