# Generated by Django 4.2.18 on 2025-02-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreomics', '0004_alter_submission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionShare',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField(null=True)),
                ('bioshare_id', models.CharField(blank=True, max_length=15, null=True)),
                ('permissions', models.JSONField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='coreomics.submission')),
            ],
        ),
    ]
