# Generated by Django 5.1.6 on 2025-03-05 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioshare', '0001_initial'),
        ('coreomics', '0004_alter_submission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionshare',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='share', to='coreomics.submission'),
        ),
    ]
