# Generated by Django 4.2.18 on 2025-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('internal_id', models.CharField(max_length=25, null=True)),
                ('submitted', models.DateTimeField(null=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
