# Generated by Django 4.2.18 on 2025-02-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreomics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='pi_email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='pi_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter_email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitter_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
