# Generated by Django 4.2.18 on 2025-02-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreomics', '0002_submission_pi_email_submission_pi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
