# Generated by Django 4.2.18 on 2025-02-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreomics', '0003_submission_submission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-submitted',)},
        ),
    ]
