# Generated by Django 5.1.6 on 2025-06-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreomics', '0004_alter_submission_options'),
        ('slims', '0023_alter_run_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreomics_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('template', models.TextField(null=True)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent', models.DateTimeField(null=True)),
                ('data', models.JSONField(null=True)),
                ('pools', models.ManyToManyField(related_name='notes', to='slims.runlane')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreomics.submission')),
            ],
        ),
    ]
